# Generated by Django 5.2 on 2025-05-11 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_bus_no_of_seats_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='Seat',
            new_name='seat',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='Features',
            new_name='features',
        ),
    ]
